- name: provising ca.cert
  hosts: clients
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: copy certs to remote hosts
      copy:
        src: /mnt/d/home/esm/B12-sum/ansible/ca.crt
        dest: /usr/local/share/ca-certificates/
    
    - name: update ca certs
      command: update-ca-certificates